name: bahodir

networks:
    net:
volumes:
    postgres_data:

services:
  auction:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: auction
    restart: unless-stopped
    networks:
      - net
    ports: 
      - 9002:9000