name: app

networks:
    net:
volumes:
    postgres_data:

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: app:latest
    container_name: app
    restart: unless-stopped
    networks:
      - net